//! Build a [`SceneSpec`] for a chapter from on-disk inputs.
//!
//! Phase B: per-paragraph timing.
//!
//! ```text
//!     ┌── Title ──┐ ┌── Para 1 ──┐ ┌── Para 2 ──┐ ┌── … ──┐ ┌── Outro ──┐
//!     0           4s              proportional to char count        D-3   D
//! ```
//!
//! The middle window (`title_end .. outro_start`) is split across the
//! body's paragraphs proportional to their character counts. A paragraph
//! whose share would exceed [`MAX_PARAGRAPH_SCENE_MS`] is subdivided into
//! sentence-balanced sub-scenes so the karaoke text reveal doesn't run
//! for two minutes off a single paragraph tile.
//!
//! Tile attachment is text-equality-driven: the publisher hands us the
//! list of `(paragraph_text, image_path)` rows from `chapter.paragraphs`,
//! and we attach an image to whichever animation paragraph contains the
//! row's text. Animation paragraphs without a matching tile still get a
//! `Paragraph` scene — the renderer just falls back to the chapter's
//! background.

use std::path::{Path, PathBuf};

use super::spec::{AudioRef, Background, ChapterMeta, Output, Scene, SceneSpec, Theme};
use super::timing::{ratio_to_ms, split_paragraphs, split_sentences};

/// Maximum runtime for a single `Paragraph` scene before we subdivide it
/// into multiple sub-scenes (driven by sentence boundaries). 60 s is a
/// soft soft-limit — past it the karaoke text reveal feels unmoored from
/// the visual. The subdivider always lands at `target_count >= 2`, so
/// the resulting sub-scenes are guaranteed to be ≤ MAX / 2 ≈ 30 s.
pub const MAX_PARAGRAPH_SCENE_MS: u64 = 60_000;

/// Per-paragraph metadata sourced from `chapter.paragraphs[]`.
///
/// Keyed by text (substring match) for attaching to scenes the
/// planner emits. An entry might carry:
///
///   * just an `image_path` (image-gen tile, Phase D),
///   * just a `visual_kind` + `visual_params` (Phase G STEM diagram),
///   * both, or neither (no entry; the publisher only emits info
///     rows for paragraphs that have at least one of the above).
///
/// Robust to small text differences between LLM passes — substring
/// matching tolerates trailing whitespace, emphasis stripping, etc.
#[derive(Debug, Clone)]
pub struct ParagraphInfo {
    pub text: String,
    /// Phase D — paragraph illustration tile (image-gen output).
    /// `None` for paragraphs that didn't produce a tile (or for
    /// STEM diagram-only paragraphs).
    pub image_path: Option<PathBuf>,
    /// Phase G — diagram template id from the visual classifier
    /// (`function_plot`, `free_body`, …). `None` for prose
    /// paragraphs and for non-STEM books that never ran the
    /// classifier.
    pub visual_kind: Option<String>,
    /// Phase G — template-specific params, free-form JSON. Only
    /// meaningful when `visual_kind` is set.
    pub visual_params: Option<serde_json::Value>,
    /// Phase H — bespoke Manim code generated by the `ManimCode` LLM
    /// for paragraphs the classifier marked `custom_manim`. `None`
    /// means the code-gen pass either hasn't run yet or returned
    /// empty (paragraph not actually visualisable); the publisher
    /// falls back to prose for those.
    pub manim_code: Option<String>,
}

/// Back-compat alias — keeps the old name for callers that haven't
/// migrated yet. New code should use `ParagraphInfo` directly.
pub type ParagraphTile = ParagraphInfo;

/// Inputs the planner needs. Kept as a plain struct so the call sites
/// (publisher + tests) don't have to wire a new function signature every
/// time we add a knob.
#[derive(Debug, Clone)]
pub struct PlanInput {
    /// Carried for log/diagnostic context — not used in the spec body
    /// today, but every caller already has it on hand and Phase D will
    /// use it for the per-paragraph tile lookup against the DB.
    #[allow(dead_code)]
    pub audiobook_id: String,
    /// Same as above: present for symmetry + future use.
    #[allow(dead_code)]
    pub language: String,
    pub chapter_number: u32,
    pub chapter_title: String,
    pub chapter_body_md: String,
    pub audio_wav: PathBuf,
    pub audio_duration_ms: u64,
    pub waveform_json: Option<PathBuf>,
    pub cover_image: Option<PathBuf>,
    /// Paragraph metadata keyed by text. Empty in Phase A/B; the
    /// publisher fills this from `chapter.paragraphs[]` (Phase D
    /// for tiles, Phase G for diagram labels). Each entry has at
    /// least one of `image_path`, `visual_kind` set.
    pub paragraph_tiles: Vec<ParagraphInfo>,
    pub output_mp4: PathBuf,
    pub theme_preset: Option<String>,
    /// Output frame rate. Sourced from `Config::animate_fps` (default
    /// 24). Tests construct `PlanInput` directly and pass an explicit
    /// fps; production goes through the publisher.
    pub fps: u32,
}

/// Build a [`SceneSpec`] from `input`.
///
/// Allocation:
///
/// * 0 …      4 000 ms — Title card.
/// * 4 000 …  D-3 000  — Paragraph scenes, char-ratio proportional.
/// * D-3 000 … D       — Outro card.
///
/// where `D = audio_duration_ms`. Chapters shorter than 8 s collapse
/// title/outro proportionally so the paragraph window stays > 0.
pub fn plan(input: PlanInput) -> SceneSpec {
    let duration = input.audio_duration_ms.max(1);
    let (title_end, outro_start) = title_and_outro_windows(duration);

    let background = match input.cover_image.as_deref() {
        Some(p) => Background::Image {
            src: p.to_path_buf(),
            kenburns: true,
        },
        None => Background::Color {
            color: "#0F172A".into(),
        },
    };

    let mut spec = SceneSpec::new(
        ChapterMeta {
            number: input.chapter_number,
            title: input.chapter_title.clone(),
            duration_ms: duration,
        },
        AudioRef {
            wav: input.audio_wav,
            peaks: input.waveform_json,
        },
        background,
        Output::hd_1080(input.output_mp4, input.fps),
    )
    .with_theme(Theme {
        preset: input.theme_preset.unwrap_or_else(|| "library".into()),
        primary: None,
        accent: None,
    });

    spec = spec.push(Scene::Title {
        start_ms: 0,
        end_ms: title_end,
        title: format!("Chapter {}", input.chapter_number),
        subtitle: Some(input.chapter_title.clone()),
    });

    // The paragraph window is everything between the title and outro
    // cards. If for any reason that's empty (extremely short chapter),
    // skip the paragraph layer entirely — the title and outro alone
    // still give the viewer something to look at.
    if outro_start > title_end {
        for scene in plan_paragraph_scenes(
            &input.chapter_body_md,
            title_end,
            outro_start,
            &input.paragraph_tiles,
        ) {
            spec = spec.push(scene);
        }
    }

    spec.push(Scene::Outro {
        start_ms: outro_start,
        end_ms: duration,
        title: input.chapter_title,
        subtitle: Some("Continue listening at listenai.app".into()),
    })
}

/// Split the paragraph window into one or more `Paragraph` scenes,
/// allocating each paragraph a slice of the window proportional to its
/// character count. Long paragraphs (> [`MAX_PARAGRAPH_SCENE_MS`]) are
/// subdivided along sentence boundaries.
///
/// Invariants the caller can rely on:
/// * The first scene starts exactly at `window_start_ms`.
/// * The last scene ends exactly at `window_end_ms`.
/// * Scenes are contiguous (no gaps, no overlaps).
fn plan_paragraph_scenes(
    body_md: &str,
    window_start_ms: u64,
    window_end_ms: u64,
    tiles: &[ParagraphTile],
) -> Vec<Scene> {
    debug_assert!(window_end_ms > window_start_ms);
    let window_ms = window_end_ms - window_start_ms;

    let paragraphs = split_paragraphs(body_md);
    if paragraphs.is_empty() {
        // Body is empty / pure whitespace. Emit a single Paragraph scene
        // covering the window with the chapter title as fallback text so
        // the renderer always has *something* to draw.
        return vec![Scene::Paragraph {
            start_ms: window_start_ms,
            end_ms: window_end_ms,
            text: String::new(),
            tile: None,
            highlight: "none".into(),
            visual_kind: None,
            visual_params: None,
            manim_code: None,
        }];
    }

    // Char counts → char-ratio time allocation. We lay each paragraph
    // out cumulatively rather than dividing the window naively so
    // rounding never accumulates a drift past the window's right edge.
    let total_chars: usize = paragraphs.iter().map(|p| p.chars().count()).sum();
    let mut out: Vec<Scene> = Vec::with_capacity(paragraphs.len());
    let mut chars_so_far: usize = 0;
    let last_idx = paragraphs.len() - 1;

    for (i, para) in paragraphs.iter().enumerate() {
        let n = para.chars().count();
        let local_start_ms = ratio_to_ms(chars_so_far, total_chars, window_ms);
        let next_chars = chars_so_far + n;
        let local_end_ms = if i == last_idx {
            // Pin the last paragraph's end to the window's right edge —
            // ratio rounding can leave a few ms gap otherwise.
            window_ms
        } else {
            ratio_to_ms(next_chars, total_chars, window_ms)
        };
        chars_so_far = next_chars;

        let scene_start = window_start_ms + local_start_ms;
        let scene_end = window_start_ms + local_end_ms;
        if scene_end <= scene_start {
            // Defensive: skip 0-duration paragraphs (only possible on a
            // pathologically empty paragraph that snuck through).
            continue;
        }

        let info = match_info(para, tiles);
        let tile = info.and_then(|i| i.image_path.clone());
        let visual_kind = info.and_then(|i| i.visual_kind.clone());
        let visual_params = info.and_then(|i| i.visual_params.clone());
        let manim_code = info.and_then(|i| i.manim_code.clone());
        let scene_duration = scene_end - scene_start;
        // Phase H — `custom_manim` paragraphs render as a single
        // LLM-authored Manim animation against the chapter audio.
        // Subdividing would re-run the same animation N times across
        // sub-windows, which is wasteful and looks weird (the diagram
        // restarts mid-paragraph). Emit one Scene with the full
        // duration regardless of MAX_PARAGRAPH_SCENE_MS.
        if scene_duration > MAX_PARAGRAPH_SCENE_MS && manim_code.is_none() {
            for sub in subdivide_paragraph(
                para,
                scene_start,
                scene_end,
                tile.clone(),
                visual_kind.clone(),
                visual_params.clone(),
            ) {
                out.push(sub);
            }
        } else {
            out.push(Scene::Paragraph {
                start_ms: scene_start,
                end_ms: scene_end,
                text: para.clone(),
                tile,
                highlight: "karaoke".into(),
                visual_kind,
                visual_params,
                manim_code,
            });
        }
    }

    // Chain seam-fix: contiguous scenes are an invariant of the timeline,
    // but ratio rounding can leave a 1-ms gap between adjacent
    // paragraphs. Walk the list once and snap each scene's `start_ms`
    // onto its predecessor's `end_ms`.
    for i in 1..out.len() {
        let prev_end = scene_end_ms(&out[i - 1]);
        let cur_start = scene_start_ms(&out[i]);
        if cur_start != prev_end {
            set_scene_start_ms(&mut out[i], prev_end);
        }
    }
    out
}

/// Split one long paragraph into smaller scenes along sentence
/// boundaries. Each sub-scene carries the same paragraph tile (Phase B
/// uses a single tile per paragraph; Phase F can revisit) but a
/// different sub-text, so the karaoke reveal stays attached to the
/// sentences currently on screen.
fn subdivide_paragraph(
    paragraph: &str,
    start_ms: u64,
    end_ms: u64,
    tile: Option<PathBuf>,
    visual_kind: Option<String>,
    visual_params: Option<serde_json::Value>,
) -> Vec<Scene> {
    let total_ms = end_ms - start_ms;
    let sentences = split_sentences(paragraph);
    if sentences.len() <= 1 {
        // No sentence boundaries to split on — fall back to time-based
        // halving so the scene at least caps out at MAX_PARAGRAPH_SCENE_MS.
        let target_count = total_ms.div_ceil(MAX_PARAGRAPH_SCENE_MS).max(2) as usize;
        return time_split_scenes(
            paragraph,
            start_ms,
            end_ms,
            target_count,
            tile,
            visual_kind,
            visual_params,
        );
    }

    let total_chars: usize = sentences.iter().map(|s| s.chars().count()).sum();
    let target_count = total_ms.div_ceil(MAX_PARAGRAPH_SCENE_MS).max(2) as usize;
    let target_chars_per_scene = total_chars.div_ceil(target_count);

    let mut out: Vec<Scene> = Vec::with_capacity(target_count);
    let mut buf = String::new();
    let mut buf_chars: usize = 0;
    let mut chars_so_far: usize = 0;

    let push_scene = |scenes: &mut Vec<Scene>,
                      buf_text: String,
                      buf_start_chars: usize,
                      buf_end_chars: usize| {
        if buf_text.trim().is_empty() {
            return;
        }
        let s_start = start_ms + ratio_to_ms(buf_start_chars, total_chars, total_ms);
        let s_end = start_ms + ratio_to_ms(buf_end_chars, total_chars, total_ms);
        scenes.push(Scene::Paragraph {
            start_ms: s_start,
            end_ms: s_end.max(s_start + 1),
            text: buf_text,
            tile: tile.clone(),
            highlight: "karaoke".into(),
            visual_kind: visual_kind.clone(),
            visual_params: visual_params.clone(),
            // Subdivision is prose-only — `custom_manim` paragraphs
            // bypass this path in `plan_paragraph_scenes`.
            manim_code: None,
        });
    };

    let mut buf_start_chars: usize = 0;
    for sentence in &sentences {
        let n = sentence.chars().count();
        let buffered = !buf.is_empty();
        let would_exceed = buf_chars + n > target_chars_per_scene;
        if buffered && would_exceed {
            push_scene(
                &mut out,
                std::mem::take(&mut buf),
                buf_start_chars,
                chars_so_far,
            );
            buf_chars = 0;
            buf_start_chars = chars_so_far;
        }
        if !buf.is_empty() {
            buf.push(' ');
        }
        buf.push_str(sentence);
        buf_chars += n;
        chars_so_far += n;
    }
    if !buf.is_empty() {
        push_scene(&mut out, buf, buf_start_chars, chars_so_far);
    }

    // Anchor edges — the first/last sub-scene must touch the parent's
    // window edges exactly to keep the chained-scene invariant in
    // `plan_paragraph_scenes` honest.
    if let Some(first) = out.first_mut() {
        set_scene_start_ms(first, start_ms);
    }
    if let Some(last) = out.last_mut() {
        set_scene_end_ms(last, end_ms);
    }
    out
}

/// Last-resort: split a paragraph by time alone (no sentence boundaries
/// available). Used when [`split_sentences`] returns a single chunk.
fn time_split_scenes(
    text: &str,
    start_ms: u64,
    end_ms: u64,
    n: usize,
    tile: Option<PathBuf>,
    visual_kind: Option<String>,
    visual_params: Option<serde_json::Value>,
) -> Vec<Scene> {
    debug_assert!(n >= 2);
    let total_ms = end_ms - start_ms;
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let s = start_ms + (total_ms * i as u64) / n as u64;
        let e = if i == n - 1 {
            end_ms
        } else {
            start_ms + (total_ms * (i + 1) as u64) / n as u64
        };
        out.push(Scene::Paragraph {
            start_ms: s,
            end_ms: e,
            // Same text on each sub-scene — without sentence breaks
            // there's no clean way to split. The karaoke reveal still
            // progresses against the scene's own clock.
            text: text.to_string(),
            tile: tile.clone(),
            highlight: "karaoke".into(),
            visual_kind: visual_kind.clone(),
            visual_params: visual_params.clone(),
            // Subdivision is prose-only.
            manim_code: None,
        });
    }
    out
}

/// Find the `ParagraphInfo` row that matches a paragraph by
/// substring. We try both directions because `chapter.paragraphs[].
/// text` may have been stripped of markdown differently than our
/// local `split_paragraphs` output. Returns the first match, or
/// `None` when no row contains/is-contained-by the paragraph prefix.
fn match_info<'a>(paragraph: &str, tiles: &'a [ParagraphInfo]) -> Option<&'a ParagraphInfo> {
    if tiles.is_empty() || paragraph.trim().is_empty() {
        return None;
    }
    // Take a normalised prefix from each side; long paragraphs match on
    // their first ~120 chars, which is plenty for distinguishing scenes.
    let needle: String = paragraph
        .chars()
        .filter(|c| !c.is_whitespace())
        .take(120)
        .collect();
    if needle.is_empty() {
        return None;
    }
    for info in tiles {
        let hay: String = info
            .text
            .chars()
            .filter(|c| !c.is_whitespace())
            .take(240)
            .collect();
        // Forward direction: full-text search.
        if hay.contains(&needle) {
            return Some(info);
        }
        // Reverse direction: take a prefix of `hay` no longer than
        // `needle`. The byte-length min would be UTF-8-unsafe (a
        // multi-byte character could fall across the cut and panic
        // on the slice — happens with em-dashes etc.); take by
        // *chars* instead so the slice always lands on a boundary.
        let prefix: String = hay.chars().take(needle.chars().count()).collect();
        if needle.contains(&prefix) {
            return Some(info);
        }
    }
    None
}

fn scene_start_ms(s: &Scene) -> u64 {
    match s {
        Scene::Title { start_ms, .. }
        | Scene::Paragraph { start_ms, .. }
        | Scene::Outro { start_ms, .. } => *start_ms,
    }
}

fn scene_end_ms(s: &Scene) -> u64 {
    match s {
        Scene::Title { end_ms, .. }
        | Scene::Paragraph { end_ms, .. }
        | Scene::Outro { end_ms, .. } => *end_ms,
    }
}

fn set_scene_start_ms(s: &mut Scene, value: u64) {
    match s {
        Scene::Title { start_ms, .. }
        | Scene::Paragraph { start_ms, .. }
        | Scene::Outro { start_ms, .. } => *start_ms = value,
    }
}

fn set_scene_end_ms(s: &mut Scene, value: u64) {
    match s {
        Scene::Title { end_ms, .. }
        | Scene::Paragraph { end_ms, .. }
        | Scene::Outro { end_ms, .. } => *end_ms = value,
    }
}

/// Pick title and outro window edges that always leave at least 1 ms in
/// the paragraph window. The defaults (4 s title, 3 s outro) collapse
/// proportionally on chapters shorter than 8 s.
fn title_and_outro_windows(duration_ms: u64) -> (u64, u64) {
    const TITLE_TARGET_MS: u64 = 4_000;
    const OUTRO_TARGET_MS: u64 = 3_000;
    let total_target = TITLE_TARGET_MS + OUTRO_TARGET_MS;
    if duration_ms > total_target + 1_000 {
        return (TITLE_TARGET_MS, duration_ms - OUTRO_TARGET_MS);
    }
    // Clamp: split the chapter 40/40/20 so paragraph stays non-empty.
    let title = duration_ms * 4 / 10;
    let outro_start = duration_ms * 8 / 10;
    (title.min(outro_start.saturating_sub(1)), outro_start)
}

/// Build the on-disk output path for a chapter's animated MP4.
/// Layout: `<storage>/<audiobook>/<language>/ch-<n>.video.mp4`.
pub fn output_mp4_path(
    storage_root: &Path,
    audiobook_id: &str,
    language: &str,
    chapter_number: u32,
) -> PathBuf {
    storage_root
        .join(audiobook_id)
        .join(language)
        .join(format!("ch-{chapter_number}.video.mp4"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn input(duration_ms: u64) -> PlanInput {
        PlanInput {
            audiobook_id: "abc".into(),
            language: "en".into(),
            chapter_number: 1,
            chapter_title: "First Steps".into(),
            chapter_body_md: "# Heading\n\nA paragraph of text.".into(),
            audio_wav: PathBuf::from("/tmp/ch-1.wav"),
            audio_duration_ms: duration_ms,
            waveform_json: None,
            cover_image: None,
            paragraph_tiles: Vec::new(),
            output_mp4: PathBuf::from("/tmp/ch-1.video.mp4"),
            theme_preset: None,
            fps: 24,
        }
    }

    /// Force-create a chapter body of the given length by repeating a
    /// fixed sentence. Useful for triggering long-paragraph behaviours
    /// without pinning an exact char count.
    fn long_body(target_chars: usize) -> String {
        let unit = "Sentence repeated to make the paragraph long enough to be interesting. ";
        let mut s = String::new();
        while s.chars().count() < target_chars {
            s.push_str(unit);
        }
        s
    }

    fn timeline_is_continuous(spec: &SceneSpec) -> bool {
        let mut last_end: Option<u64> = None;
        for s in &spec.scenes {
            let (start, end) = match s {
                Scene::Title {
                    start_ms, end_ms, ..
                }
                | Scene::Paragraph {
                    start_ms, end_ms, ..
                }
                | Scene::Outro {
                    start_ms, end_ms, ..
                } => (*start_ms, *end_ms),
            };
            if let Some(prev) = last_end {
                if start != prev {
                    eprintln!("seam break: {prev} -> {start}");
                    return false;
                }
            }
            if end <= start {
                eprintln!("zero-or-negative scene: {start}..{end}");
                return false;
            }
            last_end = Some(end);
        }
        true
    }

    fn last_end(spec: &SceneSpec) -> u64 {
        spec.scenes
            .last()
            .map(|s| match s {
                Scene::Title { end_ms, .. }
                | Scene::Paragraph { end_ms, .. }
                | Scene::Outro { end_ms, .. } => *end_ms,
            })
            .unwrap_or(0)
    }

    #[test]
    fn long_chapter_uses_default_windows() {
        let spec = plan(input(60_000));
        // Title + at least one Paragraph + Outro.
        assert!(spec.scenes.len() >= 3);
        // Title at 0..4000, Outro ends at 60000.
        match &spec.scenes[0] {
            Scene::Title {
                start_ms, end_ms, ..
            } => {
                assert_eq!(*start_ms, 0);
                assert_eq!(*end_ms, 4_000);
            }
            other => panic!("expected Title first, got {other:?}"),
        }
        assert_eq!(last_end(&spec), 60_000);
    }

    #[test]
    fn timeline_is_contiguous_and_ends_at_duration() {
        let mut inp = input(120_000);
        inp.chapter_body_md = format!(
            "{}\n\n{}\n\n{}",
            "First paragraph that is long enough to clear the merge threshold easily.".repeat(3),
            "Second paragraph also has enough body to read as a real paragraph here.".repeat(3),
            "Third short tail." // merges into the second
        );
        let spec = plan(inp);
        assert!(timeline_is_continuous(&spec));
        assert_eq!(last_end(&spec), 120_000);
    }

    #[test]
    fn short_chapter_collapses_proportionally() {
        let spec = plan(input(5_000));
        assert!(timeline_is_continuous(&spec));
        assert_eq!(last_end(&spec), 5_000);
        // Title window is non-trivial.
        match &spec.scenes[0] {
            Scene::Title {
                start_ms, end_ms, ..
            } => assert!(end_ms > start_ms),
            other => panic!("expected Title first, got {other:?}"),
        }
    }

    #[test]
    fn missing_cover_falls_back_to_color() {
        let spec = plan(input(30_000));
        assert!(matches!(spec.background, Background::Color { .. }));
    }

    #[test]
    fn cover_image_becomes_background_image() {
        let mut inp = input(30_000);
        inp.cover_image = Some(PathBuf::from("/tmp/cover.webp"));
        let spec = plan(inp);
        assert!(matches!(
            spec.background,
            Background::Image { kenburns: true, .. }
        ));
    }

    #[test]
    fn output_path_layout() {
        let p = output_mp4_path(Path::new("/data"), "ab", "en", 3);
        assert!(p.ends_with("ab/en/ch-3.video.mp4"));
    }

    #[test]
    fn long_paragraph_subdivides_along_sentences() {
        // One paragraph that, given the chapter duration, would exceed
        // MAX_PARAGRAPH_SCENE_MS. With sentence boundaries available,
        // we expect ≥ 2 sub-scenes.
        let mut inp = input(180_000); // 3 min book ⇒ paragraph window ≈ 173s
        inp.chapter_body_md = long_body(2_000);
        let spec = plan(inp);
        let para_scenes = spec
            .scenes
            .iter()
            .filter(|s| matches!(s, Scene::Paragraph { .. }))
            .count();
        assert!(
            para_scenes >= 2,
            "expected long paragraph to subdivide; got {para_scenes} paragraph scenes"
        );
        assert!(timeline_is_continuous(&spec));
        // Each sub-scene is at most MAX_PARAGRAPH_SCENE_MS + a tiny
        // rounding margin from the seam-fix step.
        for s in &spec.scenes {
            if let Scene::Paragraph {
                start_ms, end_ms, ..
            } = s
            {
                let dur = end_ms - start_ms;
                assert!(
                    dur <= MAX_PARAGRAPH_SCENE_MS + 200,
                    "sub-scene too long: {dur}ms"
                );
            }
        }
    }

    #[test]
    fn tile_attaches_when_text_overlaps() {
        let para_text = "First paragraph body that is long enough to be a paragraph on its own.";
        let mut inp = input(60_000);
        inp.chapter_body_md = para_text.to_string();
        inp.paragraph_tiles = vec![ParagraphInfo {
            text: format!("{para_text} (extra LLM-side prose)"),
            image_path: Some(PathBuf::from("/tmp/p1.webp")),
            visual_kind: None,
            visual_params: None,
            manim_code: None,
        }];
        let spec = plan(inp);
        let tile_attached = spec.scenes.iter().any(|s| {
            matches!(
                s,
                Scene::Paragraph { tile: Some(t), .. } if t.ends_with("p1.webp")
            )
        });
        assert!(tile_attached, "tile should attach via substring match");
    }

    #[test]
    fn tile_is_none_when_text_doesnt_match() {
        let mut inp = input(60_000);
        inp.chapter_body_md =
            "Chapter body about birds that are common in northern climates indeed.".into();
        inp.paragraph_tiles = vec![ParagraphInfo {
            text: "Completely unrelated text about marine biology in the deep ocean.".into(),
            image_path: Some(PathBuf::from("/tmp/wrong.webp")),
            visual_kind: None,
            visual_params: None,
            manim_code: None,
        }];
        let spec = plan(inp);
        let any_tile = spec
            .scenes
            .iter()
            .any(|s| matches!(s, Scene::Paragraph { tile: Some(_), .. }));
        assert!(!any_tile, "no tile should attach on a content mismatch");
    }

    #[test]
    fn very_short_chapter_under_30s_still_emits_paragraph_scene() {
        // 25 s chapter exercises the "duration > 8 s but < default
        // total_target window" path — title and outro use their default
        // 4 s / 3 s targets, paragraph window is 18 s.
        let mut inp = input(25_000);
        inp.chapter_body_md = "A real paragraph that comfortably clears the merge threshold so the planner gives it its own scene."
            .repeat(2);
        let spec = plan(inp);
        assert!(timeline_is_continuous(&spec));
        assert_eq!(last_end(&spec), 25_000);
        let para_count = spec
            .scenes
            .iter()
            .filter(|s| matches!(s, Scene::Paragraph { .. }))
            .count();
        assert!(para_count >= 1, "expected at least one paragraph scene");
    }

    #[test]
    fn long_paragraph_without_sentence_boundaries_falls_back_to_time_split() {
        // Single "sentence" with no terminator — the subdivider should
        // still emit multiple sub-scenes via the time-split fallback.
        let no_punct = "word ".repeat(800); // ~3.2k chars, no `.`/`?`/`!`
        let mut inp = input(180_000);
        inp.chapter_body_md = no_punct;
        let spec = plan(inp);
        assert!(timeline_is_continuous(&spec));
        assert_eq!(last_end(&spec), 180_000);
        let para_count = spec
            .scenes
            .iter()
            .filter(|s| matches!(s, Scene::Paragraph { .. }))
            .count();
        assert!(
            para_count >= 2,
            "long sentence-less paragraph should time-split; got {para_count}"
        );
    }

    #[test]
    fn empty_body_still_produces_a_valid_timeline() {
        let mut inp = input(30_000);
        inp.chapter_body_md = "   \n\n   ".into();
        let spec = plan(inp);
        assert!(timeline_is_continuous(&spec));
        assert_eq!(last_end(&spec), 30_000);
    }
}
