/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retry_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_llms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_llm"];
        trace?: never;
    };
    "/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["system_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_user"];
        trace?: never;
    };
    "/admin/users/{id}/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revoke_sessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_voices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/voice/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_voice"];
        trace?: never;
    };
    "/audiobook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audiobook/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_one"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["patch"];
        trace?: never;
    };
    "/audiobook/{id}/chapter/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_chapter"];
        trace?: never;
    };
    "/audiobook/{id}/chapter/{n}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chapter_audio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audiobook/{id}/chapter/{n}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["regenerate_chapter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audiobook/{id}/chapter/{n}/regenerate-audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["regenerate_chapter_audio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audiobook/{id}/chapter/{n}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chapter_waveform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audiobook/{id}/generate-audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate_audio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audiobook/{id}/generate-chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate_chapters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audiobook/{id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_for_audiobook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. Cheap, no I/O. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_llms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_me"];
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe. Verifies the DB connection answers a trivial query. */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["random"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_voices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminJobList: {
            items: components["schemas"]["AdminJobRow"][];
        };
        AdminJobRow: {
            /** Format: int32 */
            attempts: number;
            audiobook_id?: string | null;
            /** Format: int32 */
            chapter_number?: number | null;
            /** Format: date-time */
            finished_at?: string | null;
            id: components["schemas"]["JobId"];
            kind: components["schemas"]["JobKind"];
            last_error?: string | null;
            /** Format: int32 */
            max_attempts: number;
            parent_id?: string | null;
            /** Format: float */
            progress_pct: number;
            /** Format: date-time */
            queued_at: string;
            /** Format: date-time */
            started_at?: string | null;
            status: components["schemas"]["JobStatus"];
            user_id?: string | null;
        };
        AdminLlmList: {
            items: components["schemas"]["AdminLlmRow"][];
        };
        AdminLlmRow: {
            /** Format: int32 */
            context_window: number;
            /** Format: double */
            cost_completion_per_1k: number;
            /** Format: double */
            cost_prompt_per_1k: number;
            default_for: string[];
            enabled: boolean;
            id: components["schemas"]["LlmId"];
            model_id: string;
            name: string;
            provider: string;
        };
        AdminUserList: {
            items: components["schemas"]["AdminUserRow"][];
            /** Format: int32 */
            total: number;
        };
        AdminUserRow: {
            /**
             * Format: int32
             * @description Count of non-revoked, non-expired sessions at query time.
             */
            active_sessions: number;
            /** Format: date-time */
            created_at: string;
            display_name: string;
            email: string;
            /** Format: date-time */
            email_verified_at?: string | null;
            id: components["schemas"]["UserId"];
            role: components["schemas"]["UserRole"];
            tier: components["schemas"]["UserTier"];
        };
        AdminVoiceList: {
            items: components["schemas"]["AdminVoiceRow"][];
        };
        AdminVoiceRow: {
            accent: string;
            enabled: boolean;
            gender: string;
            id: components["schemas"]["VoiceId"];
            language: string;
            name: string;
            premium_only: boolean;
            provider: string;
            provider_voice_id: string;
            sample_url?: string | null;
        };
        AudiobookDetail: components["schemas"]["AudiobookSummary"] & {
            chapters: components["schemas"]["ChapterSummary"][];
        };
        /** @description Identifier for an audiobook record. */
        AudiobookId: string;
        AudiobookJobList: {
            audiobook_id: string;
            jobs: components["schemas"]["JobSnapshot"][];
        };
        /** @enum {string} */
        AudiobookLength: "short" | "medium" | "long";
        AudiobookList: {
            items: components["schemas"]["AudiobookSummary"][];
        };
        /** @enum {string} */
        AudiobookStatus: "draft" | "outline_pending" | "outline_ready" | "chapters_running" | "text_ready" | "audio_ready" | "failed";
        AudiobookSummary: {
            available_languages: string[];
            /** Format: date-time */
            created_at: string;
            genre?: string | null;
            /** @description `true` when a cover image has been generated and is available at `GET /audiobook/:id/cover`. */
            has_cover: boolean;
            id: components["schemas"]["AudiobookId"];
            /** @description BCP-47 code for the primary language. */
            language: string;
            length: components["schemas"]["AudiobookLength"];
            status: components["schemas"]["AudiobookStatus"];
            title: string;
            topic: string;
            /** @description Voice picked for narration (`null` when the server default is used). */
            voice_id?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        AuthResponse: {
            access_token: string;
            /** Format: int64 */
            access_token_expires_in: number;
            refresh_token: string;
            user: components["schemas"]["User"];
        };
        /** @description Identifier for a chapter record. */
        ChapterId: string;
        /** @enum {string} */
        ChapterStatus: "pending" | "running" | "text_ready" | "audio_ready" | "failed";
        ChapterSummary: {
            body_md?: string | null;
            /** Format: int64 */
            duration_ms?: number | null;
            id: components["schemas"]["ChapterId"];
            language: string;
            /** Format: int32 */
            number: number;
            status: components["schemas"]["ChapterStatus"];
            synopsis?: string | null;
            /** Format: int32 */
            target_words?: number | null;
            title: string;
        };
        CreateAudiobookRequest: {
            /** @description Optional pre-generated cover artwork (raw base64, no `data:` prefix). */
            cover_image_base64?: string | null;
            genre?: string | null;
            /** @description BCP-47 language code, e.g. `"en"`, `"nl"`. Defaults to `"en"`. */
            language?: string | null;
            length: components["schemas"]["AudiobookLength"];
            topic: string;
            /** @description Optional voice id from `/voices`. If omitted, the TTS layer falls back to the configured `xai_default_voice`. */
            voice_id?: string | null;
        };
        CoverPreviewRequest: {
            genre?: string | null;
            topic: string;
        };
        CoverPreviewResponse: {
            image_base64: string;
            mime_type: string;
        };
        DbReadiness: {
            path: string;
            reachable: boolean;
        };
        /**
         * @description Wire-format error body. Returned by the API layer for every non-2xx
         *     response. `request_id` is populated from the `x-request-id` header.
         */
        ErrorBody: {
            code: string;
            message: string;
            request_id?: string | null;
        };
        Health: {
            service: string;
            status: string;
            version: string;
        };
        /** @description Identifier for a job record. */
        JobId: string;
        /** @enum {string} */
        JobKind: "outline" | "chapters" | "tts" | "tts_chapter" | "post_process" | "cover" | "gc" | "translate";
        JobSnapshot: {
            /** Format: int32 */
            attempts: number;
            /** Format: int32 */
            chapter_number?: number | null;
            id: string;
            kind: string;
            last_error?: string | null;
            /** Format: float */
            progress_pct: number;
            status: string;
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "completed" | "failed" | "throttled" | "dead";
        Llm: {
            /** Format: int32 */
            context_window: number;
            /** Format: double */
            cost_completion_per_1k: number;
            /** Format: double */
            cost_prompt_per_1k: number;
            default_for: components["schemas"]["LlmRole"][];
            enabled: boolean;
            id: components["schemas"]["LlmId"];
            /** @description Upstream model identifier (e.g. `anthropic/claude-sonnet-4.6`). */
            model_id: string;
            name: string;
            provider: components["schemas"]["LlmProvider"];
        };
        /** @description Identifier for an LLM configuration record. */
        LlmId: string;
        LlmList: {
            items: components["schemas"]["Llm"][];
        };
        /** @enum {string} */
        LlmProvider: "open_router";
        /**
         * @description Where this LLM is allowed to be used by default.
         * @enum {string}
         */
        LlmRole: "outline" | "chapter" | "title" | "random_topic" | "moderation" | "cover_art";
        LoginRequest: {
            email: string;
            password: string;
        };
        LogoutRequest: {
            refresh_token: string;
        };
        MeResponse: {
            user: components["schemas"]["User"];
        };
        /**
         * @description Wire event streamed to clients over the WebSocket.
         *
         *     `#[serde(tag = "type")]` keeps the JSON shape ergonomic for the
         *     TS client: `{ type: "progress", ... }`, `{ type: "completed", ... }`.
         */
        ProgressEvent: {
            /** Format: date-time */
            at: string;
            audiobook_id: string;
            jobs: components["schemas"]["JobSnapshot"][];
            /** @enum {string} */
            type: "snapshot";
        } | {
            /** Format: date-time */
            at: string;
            audiobook_id?: string | null;
            /** Format: int32 */
            chapter?: number | null;
            /** Format: int64 */
            eta_seconds?: number | null;
            job_id: string;
            kind: string;
            /** Format: float */
            pct: number;
            stage: string;
            /** @enum {string} */
            type: "progress";
        } | {
            /** Format: date-time */
            at: string;
            audiobook_id?: string | null;
            job_id: string;
            kind: string;
            /** @enum {string} */
            type: "completed";
        } | {
            /** Format: date-time */
            at: string;
            audiobook_id?: string | null;
            error: string;
            job_id: string;
            kind: string;
            /** @enum {string} */
            type: "failed";
        };
        RandomTopicRequest: {
            /** @description Optional seed or theme hint, e.g. "sci-fi", "history of Korea". */
            seed?: string | null;
        };
        RandomTopicResponse: {
            genre: string;
            length: components["schemas"]["AudiobookLength"];
            topic: string;
        };
        ReadinessReport: {
            db: components["schemas"]["DbReadiness"];
            status: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        RegisterRequest: {
            display_name: string;
            email: string;
            password: string;
        };
        RevokeSessionsResponse: {
            /** Format: int32 */
            revoked: number;
        };
        SystemOverview: {
            /** Format: int32 */
            audiobooks_total: number;
            /** Format: int32 */
            chapters_total: number;
            db_path: string;
            /** Format: int32 */
            jobs_completed_24h: number;
            /** Format: int32 */
            jobs_dead: number;
            /** Format: int32 */
            jobs_queued: number;
            /** Format: int32 */
            jobs_running: number;
            llm_mock_mode: boolean;
            /** Format: int64 */
            storage_bytes: number;
            storage_path: string;
            tts_mock_mode: boolean;
            /** Format: int32 */
            users_total: number;
        };
        UpdateAudiobookRequest: {
            genre?: string | null;
            title?: string | null;
            voice_id?: string | null;
        };
        TranslateRequest: {
            target_language: string;
            source_language?: string | null;
        };
        TranslateResponse: {
            job_id: string;
            target_language: string;
            source_language: string;
        };
        UpdateChapterRequest: {
            body_md?: string | null;
            synopsis?: string | null;
            title?: string | null;
        };
        UpdateLlmRequest: {
            /** Format: double */
            cost_completion_per_1k?: number | null;
            /** Format: double */
            cost_prompt_per_1k?: number | null;
            default_for?: string[] | null;
            enabled?: boolean | null;
            name?: string | null;
        };
        CreateLlmRequest: {
            /** @description Snake-case identifier; `[a-z0-9_]+`. */
            id: string;
            name: string;
            /** @description Upstream model id, e.g. `google/gemini-2.5-flash-image`. */
            model_id: string;
            /** Format: int32 */
            context_window: number;
            /** Format: double */
            cost_prompt_per_1k: number;
            /** Format: double */
            cost_completion_per_1k: number;
            enabled?: boolean | null;
            default_for?: string[] | null;
        };
        UpdateMeRequest: {
            display_name?: string | null;
        };
        UpdateUserRequest: {
            role?: null | components["schemas"]["UserRole"];
            tier?: null | components["schemas"]["UserTier"];
        };
        UpdateVoiceRequest: {
            accent?: string | null;
            enabled?: boolean | null;
            name?: string | null;
            premium_only?: boolean | null;
            sample_url?: string | null;
        };
        User: {
            /** Format: date-time */
            created_at: string;
            display_name: string;
            email: string;
            /** Format: date-time */
            email_verified_at?: string | null;
            id: components["schemas"]["UserId"];
            role: components["schemas"]["UserRole"];
            tier: components["schemas"]["UserTier"];
        };
        /** @description Identifier for a user record. */
        UserId: string;
        /** @enum {string} */
        UserRole: "user" | "admin";
        /** @enum {string} */
        UserTier: "free" | "pro";
        Voice: {
            accent: string;
            enabled: boolean;
            gender: components["schemas"]["VoiceGender"];
            id: components["schemas"]["VoiceId"];
            language: string;
            name: string;
            premium_only: boolean;
            /** @description Upstream provider, e.g. `"xai"`. */
            provider: string;
            /** @description Provider's own identifier for this voice (e.g. `"eve"`). */
            provider_voice_id: string;
            sample_url?: string | null;
        };
        /** @enum {string} */
        VoiceGender: "female" | "male" | "neutral";
        /** @description Identifier for a voice record. */
        VoiceId: string;
        VoiceList: {
            items: components["schemas"]["Voice"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobList"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_llms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLlmList"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_llm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLlmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLlmRow"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    system_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOverview"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserList"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRow"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count of sessions revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeSessionsResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_voices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminVoiceList"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_voice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVoiceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminVoiceRow"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All audiobooks owned by the authed user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookList"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAudiobookRequest"];
            };
        };
        responses: {
            /** @description Outline ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookDetail"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream LLM error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audiobook id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audiobook + chapters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAudiobookRequest"];
            };
        };
        responses: {
            /** @description Updated audiobook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookDetail"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_chapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChapterRequest"];
            };
        };
        responses: {
            /** @description Updated chapter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummary"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chapter_audio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WAV bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regenerate_chapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regenerated chapter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummary"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream LLM error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regenerate_chapter_audio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regenerated chapter audio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummary"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream TTS error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chapter_waveform: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON peaks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_audio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted, TTS started in background */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Chapters not ready to narrate */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_chapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted, generation started in background */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already running or not in outline_ready */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_for_audiobook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audiobook id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest status of every job for this audiobook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookJobList"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid, expired, or revoked refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created + token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_llms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled LLM configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmList"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
        };
    };
    random: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RandomTopicRequest"];
            };
        };
        responses: {
            /** @description A random audiobook topic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomTopicResponse"];
                };
            };
            /** @description LLM error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_voices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled voices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceList"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
