// Re-exports of the generated schema's component types, with the verbose
// `components["schemas"]["…"]` path flattened into readable aliases.
//
// The generated file is regenerated by `npm run gen:api` against
// `../shared/openapi.json`. Keep this module hand-maintained so a breaking
// schema change surfaces as a TypeScript error in every call-site at once.

import type { components } from "./schema";

type S = components["schemas"];

export type AudiobookSummary = S["AudiobookSummary"];
export type AudiobookDetail = S["AudiobookDetail"];
export type AudiobookList = S["AudiobookList"];
export type ChapterSummary = S["ChapterSummary"];
export type AudiobookLength = S["AudiobookLength"];
export type AudiobookStatus = S["AudiobookStatus"];
export type ChapterStatus = S["ChapterStatus"];

export type CreateAudiobookRequest = S["CreateAudiobookRequest"];
export type UpdateAudiobookRequest = S["UpdateAudiobookRequest"];
export type UpdateChapterRequest = S["UpdateChapterRequest"];

export type LoginRequest = S["LoginRequest"];
export type RegisterRequest = S["RegisterRequest"];
export type RefreshRequest = S["RefreshRequest"];
export type LogoutRequest = S["LogoutRequest"];
export type AuthResponse = S["AuthResponse"];
export type MeResponse = S["MeResponse"];
export type UpdateMeRequest = S["UpdateMeRequest"];
export type User = S["User"];

export type VoiceList = S["VoiceList"];
export type LlmList = S["LlmList"];
export type Voice = S["Voice"];
export type Llm = S["Llm"];

export type RandomTopicRequest = S["RandomTopicRequest"];
export type RandomTopicResponse = S["RandomTopicResponse"];

export type CoverPreviewRequest = S["CoverPreviewRequest"];
export type CoverPreviewResponse = S["CoverPreviewResponse"];
export type LlmRole = S["LlmRole"];
export type TranslateRequest = S["TranslateRequest"];
export type TranslateResponse = S["TranslateResponse"];

export type AudiobookJobList = S["AudiobookJobList"];
export type JobSnapshot = S["JobSnapshot"];
export type JobKind = S["JobKind"];
export type JobStatus = S["JobStatus"];
export type ProgressEvent = S["ProgressEvent"];

export type ErrorBody = S["ErrorBody"];

// --- admin ---------------------------------------------------------------
export type SystemOverview = S["SystemOverview"];
export type AdminLlmRow = S["AdminLlmRow"];
export type AdminLlmList = S["AdminLlmList"];
export type UpdateLlmRequest = S["UpdateLlmRequest"];
export type CreateLlmRequest = S["CreateLlmRequest"];
export type AdminVoiceRow = S["AdminVoiceRow"];
export type AdminVoiceList = S["AdminVoiceList"];
export type UpdateVoiceRequest = S["UpdateVoiceRequest"];
export type AdminUserRow = S["AdminUserRow"];
export type AdminUserList = S["AdminUserList"];
export type UpdateUserRequest = S["UpdateUserRequest"];
export type RevokeSessionsResponse = S["RevokeSessionsResponse"];
export type AdminJobRow = S["AdminJobRow"];
export type AdminJobList = S["AdminJobList"];
export type UserRole = S["UserRole"];
export type UserTier = S["UserTier"];

// --- admin test endpoints ------------------------------------------------
// Hand-written (not generated) because the frontend doesn't always
// regenerate `schema.d.ts`; these mirror the utoipa-derived Rust structs
// in `backend/api/src/handlers/admin.rs`.
export interface TestLlmRequest {
  llm_id: string;
  prompt: string;
  system?: string | null;
  temperature?: number | null;
  max_tokens?: number | null;
}
export interface TestLlmResponse {
  content: string;
  prompt_tokens: number;
  completion_tokens: number;
  mocked: boolean;
}
export interface TestVoiceRequest {
  voice_id: string;
  text: string;
}
export interface TestVoiceResponse {
  audio_wav_base64: string;
  sample_rate_hz: number;
  duration_ms: number;
  mocked: boolean;
}
