// Re-exports of the generated schema's component types, with the verbose
// `components["schemas"]["…"]` path flattened into readable aliases.
//
// The generated file is regenerated by `npm run gen:api` against
// `../shared/openapi.json`. Keep this module hand-maintained so a breaking
// schema change surfaces as a TypeScript error in every call-site at once.

import type { components } from "./schema";

type S = components["schemas"];

// `art_style` is intersected here because the cached `shared/openapi.json`
// snapshot doesn't yet know about it; once the file is regenerated the
// schema types will already carry the field and the intersections become
// no-ops.
type WithArtStyle = {
  art_style?: string | null;
  /** Pinned LLM id for cover + chapter art generation. */
  cover_llm_id?: string | null;
  /** Tiles per visual paragraph (0..=3). */
  images_per_paragraph?: number | null;
  /** User-defined library bucket. `null` = "Uncategorized". */
  category?: string | null;
  /** Podcast id this audiobook is assigned to, or `null` when unassigned. */
  podcast_id?: string | null;
  /**
   * X.ai TTS speech-tag palette suggested by the outline LLM
   * (e.g. `["[pause]", "<whisper>", "<soft>"]`). The chapter
   * writer embeds these inline in the prose so the narrator
   * delivers them. Empty = plain narration.
   */
  tags?: string[] | null;
  /**
   * Total narration runtime for the primary-language chapters,
   * in milliseconds. `null` until at least one chapter has been
   * narrated.
   */
  duration_ms?: number | null;
  /**
   * `true` when the book is rendered as a YouTube Short: a single
   * ≤ 90 s chapter with a vertical 9:16 cover, uploaded as a
   * single vertical video.
   */
  is_short?: boolean | null;
  /**
   * LLM verdict on whether the topic is STEM (math / physics /
   * chemistry / biology / CS / engineering). Set during outline
   * generation. Null on legacy rows or fresh drafts.
   */
  stem_detected?: boolean | null;
  /**
   * User override of the LLM-detected STEM flag. Null means
   * "trust the detection". `true`/`false` overrides regardless.
   */
  stem_override?: boolean | null;
  /**
   * Effective STEM flag the renderer uses (override > detected >
   * false). Pre-computed by the backend so the UI doesn't have to
   * repeat the fallback logic.
   */
  is_stem?: boolean | null;
  /**
   * `true` when the audiobook narrates with per-role voices
   * (narrator + dialogue_male + dialogue_female). The role-to-voice
   * map lives in `voice_roles`.
   */
  multi_voice_enabled?: boolean | null;
  /**
   * `{ role: voice_id }` map for multi-voice narration. Roles
   * outside `narrator | dialogue_male | dialogue_female` are
   * ignored by the audio pipeline.
   */
  voice_roles?: Record<string, string> | null;
};

export interface ParagraphSummary {
  /** Stable index into the chapter's paragraph array. */
  index: number;
  /** Character count of the paragraph body — used to time-slot the slideshow. */
  char_count: number;
  /** Whether the LLM extract pass marked this paragraph as visual. */
  is_visual: boolean;
  /**
   * Tiles persisted so far (1..=image_count addressable on the
   * `/paragraph/:p/image/:i` stream endpoint).
   */
  image_count: number;
  /**
   * Phase G — diagram template id picked by the per-paragraph
   * visual classifier (`function_plot`, `free_body`, `equation_steps`,
   * …). `null` for prose paragraphs and for non-STEM books that
   * never ran the classifier. Drives the future Manim render path
   * + the diagram-count badge on AnimationRow.
   */
  visual_kind?: string | null;
}

type WithChapterExtras = {
  /** Per-paragraph metadata; empty when paragraph art wasn't requested. */
  paragraphs?: ParagraphSummary[];
};

export type AudiobookSummary = S["AudiobookSummary"] & WithArtStyle;
export type ChapterSummary = S["ChapterSummary"] & WithChapterExtras;
export type AudiobookDetail = Omit<S["AudiobookDetail"], "chapters"> &
  WithArtStyle & {
    chapters: ChapterSummary[];
  };
export type AudiobookList = Omit<S["AudiobookList"], "items"> & {
  items: AudiobookSummary[];
};
export type AudiobookLength = S["AudiobookLength"];
export type AudiobookStatus = S["AudiobookStatus"];
export type ChapterStatus = S["ChapterStatus"];

export interface AutoPublishPipeline {
  /** `"single"` (one concatenated video) or `"playlist"`. Defaults to single. */
  mode?: "single" | "playlist" | null;
  privacy_status?: "private" | "unlisted" | "public" | null;
  /** When true, the publish stops after encoding for review. */
  review?: boolean;
}

export interface AutoPipeline {
  /** Enqueue the chapter-writing job after outline. */
  chapters: boolean;
  /**
   * Enqueue cover-art generation alongside chapters. Ignored if the
   * caller already supplied `cover_image_base64`.
   */
  cover?: boolean;
  /** Enqueue narration after chapters. Ignored when chapters is false. */
  audio: boolean;
  /** Optional YouTube publish step after narration. */
  publish?: AutoPublishPipeline | null;
}

export type CreateAudiobookRequest = S["CreateAudiobookRequest"] &
  WithArtStyle & {
    auto_pipeline?: AutoPipeline | null;
  };
export type UpdateAudiobookRequest = S["UpdateAudiobookRequest"] &
  WithArtStyle & {
    /**
     * Three-state STEM override:
     *   field absent          → don't change
     *   `null`                → clear (use LLM detection)
     *   `true` / `false`      → force the value
     * `undefined` here matches "field absent"; use `null` when you
     * mean "clear".
     */
    stem_override?: boolean | null;
  };
export type UpdateChapterRequest = S["UpdateChapterRequest"];

export type LoginRequest = S["LoginRequest"];
export type RegisterRequest = S["RegisterRequest"];
export type RefreshRequest = S["RefreshRequest"];
export type LogoutRequest = S["LogoutRequest"];
export type AuthResponse = S["AuthResponse"];
export type MeResponse = S["MeResponse"];
export type UpdateMeRequest = S["UpdateMeRequest"];
export type User = S["User"];

export type VoiceList = S["VoiceList"];
export type Voice = S["Voice"];
// `function`/`languages`/`priority` were added after the cached schema
// snapshot was generated; intersection here keeps callers type-safe until
// `npm run gen:api` is re-run.
//
// `default_for` is also widened: the backend's `LlmRole` enum has gained
// `manim_code`, `translate`, and `voice_extract` since the schema was
// last regenerated. Re-running `npm run gen:api` collapses the widening
// into a no-op once the schema catches up.
export type ExtraLlmRole = "manim_code" | "translate" | "voice_extract";
export type LlmRole = S["LlmRole"] | ExtraLlmRole;
export type Llm = Omit<S["Llm"], "default_for"> & {
  default_for: LlmRole[];
  function?: string | null;
  languages?: string[];
  priority?: number;
  /** Per-megapixel price for image-generation models. */
  cost_per_megapixel?: number;
};
export type LlmList = Omit<S["LlmList"], "items"> & { items: Llm[] };

// Intersected because the cached `shared/openapi.json` snapshot doesn't
// yet include `language`; once the schema is regenerated the intersection
// becomes a no-op.
export type RandomTopicRequest = S["RandomTopicRequest"] & {
  language?: string | null;
};
export type RandomTopicResponse = S["RandomTopicResponse"];

export type CoverPreviewRequest = S["CoverPreviewRequest"] & WithArtStyle & {
  /** Override the picker for this preview. */
  llm_id?: string | null;
  /** Render a vertical 9:16 cover for a YouTube Short. Defaults to false. */
  is_short?: boolean | null;
};
export type CoverPreviewResponse = S["CoverPreviewResponse"];
// `LlmRole` is exported above with the `ExtraLlmRole` widening — keep
// this comment as a reminder so a future schema regen drops the alias
// instead of leaving a duplicate.
export type TranslateRequest = S["TranslateRequest"];
export type TranslateResponse = S["TranslateResponse"];

export type AudiobookJobList = S["AudiobookJobList"];
export type JobSnapshot = S["JobSnapshot"];
export type JobKind = S["JobKind"];
export type JobStatus = S["JobStatus"];
export type ProgressEvent = S["ProgressEvent"];

export type ErrorBody = S["ErrorBody"];

// --- admin ---------------------------------------------------------------
export type SystemOverview = S["SystemOverview"];

// `function`/`languages`/`priority` (and `model_id`/`context_window` on
// patch) are intersected because the cached `shared/openapi.json` snapshot
// hasn't been regenerated yet. Once it is, the schema types will already
// carry these fields and the intersections become no-ops.
type LlmExtra = {
  function?: string | null;
  languages?: string[] | null;
  priority?: number | null;
  /** Per-megapixel price for image-generation models. */
  cost_per_megapixel?: number | null;
  /** Upstream provider — `open_router` (default) or `xai`. */
  provider?: string | null;
};
type LlmPatchExtra = LlmExtra & {
  model_id?: string | null;
  context_window?: number | null;
};

export type AdminLlmRow = S["AdminLlmRow"] & LlmExtra;
export type AdminLlmList = Omit<S["AdminLlmList"], "items"> & {
  items: AdminLlmRow[];
};
export type UpdateLlmRequest = S["UpdateLlmRequest"] & LlmPatchExtra;
export type CreateLlmRequest = S["CreateLlmRequest"] & LlmExtra;
export type AdminVoiceRow = S["AdminVoiceRow"];
export type AdminVoiceList = S["AdminVoiceList"];
export type UpdateVoiceRequest = S["UpdateVoiceRequest"];
export type AdminUserRow = S["AdminUserRow"];
export type AdminUserList = S["AdminUserList"];
export type UpdateUserRequest = S["UpdateUserRequest"];
export type RevokeSessionsResponse = S["RevokeSessionsResponse"];
export type AdminJobRow = S["AdminJobRow"];
export type AdminJobList = S["AdminJobList"];
export type UserRole = S["UserRole"];
export type UserTier = S["UserTier"];

// --- openrouter catalog --------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/admin.rs`.

export interface OpenRouterModelRow {
  id: string;
  name: string;
  description: string | null;
  context_length: number | null;
  input_modalities: string[];
  output_modalities: string[];
  /** USD per 1k prompt tokens (already converted from per-token). */
  cost_prompt_per_1k: number;
  cost_completion_per_1k: number;
  /** USD per generated image, if the upstream priced one. */
  cost_per_image: number;
}

export interface OpenRouterModelList {
  items: OpenRouterModelRow[];
}

// --- xAI catalog ---------------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/admin.rs::list_xai_models`.

export interface XaiModelRow {
  id: string;
  aliases: string[];
  input_modalities: string[];
  output_modalities: string[];
  /** USD per 1k prompt tokens (already converted from xAI's encoding). */
  cost_prompt_per_1k: number;
  cost_completion_per_1k: number;
  context_length: number | null;
}

export interface XaiModelList {
  items: XaiModelRow[];
}

export interface XaiImageModelRow {
  id: string;
  aliases: string[];
  input_modalities: string[];
  output_modalities: string[];
  /** USD per generated image (already converted from xAI's microdollars). */
  cost_per_image: number;
  context_length: number | null;
}

export interface XaiImageModelList {
  items: XaiImageModelRow[];
}

// --- YouTube settings ----------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/admin.rs::YoutubeFooterRow`.

export interface YoutubeFooterRow {
  /** BCP-47 language code (also the record id). */
  language: string;
  text: string;
  updated_at: string;
}

export interface YoutubeFooterList {
  items: YoutubeFooterRow[];
}

export interface UpsertYoutubeFooterRequest {
  text: string;
}

export interface YoutubePublishSettings {
  /**
   * When true, the publisher appends a "Models used" block to every
   * YouTube description it generates (built from the audiobook's
   * `generation_event` log).
   */
  include_credits: boolean;
  /**
   * When true, the encoder burns a "Like & Subscribe!" call-to-action
   * onto every newly-encoded YouTube video for two short windows (a
   * few seconds in and again before the end). Off by default.
   */
  like_subscribe_overlay: boolean;
}

// --- audiobook categories ------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/admin.rs` and
// `catalog.rs`.

export interface AudiobookCategoryRow {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
  /** How many audiobooks currently use this category. */
  usage_count: number;
}

export interface AudiobookCategoryList {
  items: AudiobookCategoryRow[];
}

export interface CreateAudiobookCategoryRequest {
  name: string;
}

export interface UpdateAudiobookCategoryRequest {
  name: string;
}

export interface AudiobookCategoryName {
  name: string;
}

export interface AudiobookCategoryNameList {
  items: AudiobookCategoryName[];
}

// --- chapter LLM test (Manim code-gen) -----------------------------------
// Hand-written; mirrors `backend/api/src/handlers/audiobook.rs::test_chapter_manim_llm`.

export interface TestChapterManimLlmRequest {
  /** LLM record id (e.g. `claude_sonnet_4_6`). */
  llm_id: string;
  /** Optional paragraph index. Defaults to first custom_manim or 0. */
  paragraph_index?: number;
  /** Theme name; defaults to "library". */
  theme?: string;
}

export interface TestChapterManimLlmResponse {
  llm_name: string;
  model_id: string;
  /** Rendered prompt body actually sent to the LLM. */
  prompt: string;
  /** Raw response from the LLM (typically `{"summary":..,"code":..}`). */
  response: string;
  cost_usd: number;
  elapsed_ms: number;
  prompt_tokens: number;
  completion_tokens: number;
  mocked: boolean;
  paragraph_index: number;
  paragraph_preview: string;
}

export interface RenderTestManimRequest {
  /** Raw `class Scene(TemplateScene): …` Python source. */
  code: string;
  /** Target run length; defaults to 8 s on the backend. */
  duration_ms?: number;
}

export interface RenderTestManimResponse {
  /** UUID; pair with `audiobookTestManimVideoUrl(id, test_id)`. */
  test_id: string;
  /** Wall-clock time the Manim sidecar took. */
  elapsed_ms: number;
}

// --- audiobook costs -----------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/audiobook.rs::costs`.

export interface CostByRole {
  role: string;
  count: number;
  prompt_tokens: number;
  completion_tokens: number;
  cost_usd: number;
  /** LLM record id; absent when the row was deleted/renamed. */
  llm_id?: string;
  /**
   * Human-readable model name (e.g. "Claude Sonnet 4.6"). For TTS rows
   * this carries the voice id parsed from the event note instead, so the
   * breakdown can render "Eve" rather than the placeholder LLM.
   */
  llm_name?: string;
  /** Upstream slug (e.g. "anthropic/claude-sonnet-4.6"). */
  model_id?: string;
}

export interface AudiobookCostSummary {
  audiobook_id: string;
  total_cost_usd: number;
  total_prompt_tokens: number;
  total_completion_tokens: number;
  event_count: number;
  by_role: CostByRole[];
}

// --- topic templates -----------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/topic_templates.rs`.

export interface TopicTemplate {
  id: string;
  title: string;
  topic: string;
  genre: string | null;
  length: AudiobookLength | null;
  language: string | null;
  sort_order: number;
  enabled: boolean;
  /** Defaults the New Audiobook form's "YouTube Short" toggle on apply. */
  is_short: boolean;
  created_at: string;
  updated_at: string;
}

export interface TopicTemplateList {
  items: TopicTemplate[];
}

export interface CreateTopicTemplateRequest {
  title: string;
  topic: string;
  genre?: string | null;
  length?: AudiobookLength | null;
  language?: string | null;
  sort_order?: number | null;
  enabled?: boolean | null;
  is_short?: boolean | null;
}

export interface UpdateTopicTemplateRequest {
  title?: string | null;
  topic?: string | null;
  genre?: string | null;
  /** Wrapped: `null` clears the default; omitted leaves it untouched. */
  length?: AudiobookLength | null;
  language?: string | null;
  sort_order?: number | null;
  enabled?: boolean | null;
  is_short?: boolean | null;
}

// --- integrations (YouTube) ----------------------------------------------
// Hand-written to match `backend/api/src/handlers/integrations.rs`.

export interface OauthStartResponse {
  url: string;
}

export interface YoutubeAccountStatus {
  connected: boolean;
  channel_title: string | null;
  connected_at: string | null;
}

export type PublishMode = "single" | "playlist";

export interface PublishYoutubeRequest {
  language: string;
  privacy_status?: "private" | "unlisted" | "public" | null;
  /** `"single"` (one concatenated video) or `"playlist"` (one video per chapter). */
  mode?: PublishMode | null;
  /** When true, encode but do not upload — wait for explicit approval. */
  review?: boolean | null;
  /** When true, use the per-chapter animated companion videos as the
   * visual track (requires every chapter to have completed the
   * `animate` job; the API 409s otherwise). */
  animate?: boolean | null;
  description?: string | null;
  /**
   * Per-video override for the "Like & Subscribe!" overlay.
   *   `null` / omitted → inherit the global admin setting.
   *   `true` / `false` → force on/off for this publication.
   */
  like_subscribe_overlay?: boolean | null;
}

export interface PublishYoutubeResponse {
  job_id: string;
  publication_id: string;
}

export interface ApprovePublicationResponse {
  job_id: string;
  publication_id: string;
}

export interface PublicationVideoRow {
  chapter_number: number;
  title: string;
  video_id: string | null;
  video_url: string | null;
  published_at: string | null;
  last_error: string | null;
}

export interface PublicationRow {
  id: string;
  language: string;
  privacy_status: "private" | "unlisted" | "public";
  mode: PublishMode;
  /** True while waiting for explicit approval after preview encoding. */
  review: boolean;
  /** ISO timestamp at which the preview MP4(s) became available. */
  preview_ready_at: string | null;
  video_id: string | null;
  video_url: string | null;
  playlist_id: string | null;
  playlist_url: string | null;
  published_at: string | null;
  last_error: string | null;
  created_at: string;
  updated_at: string;
  videos: PublicationVideoRow[];
  /** Per-publication override; `null` means it inherits the global. */
  like_subscribe_overlay: boolean | null;
}

export interface PublicationList {
  items: PublicationRow[];
}

// --- admin test endpoints ------------------------------------------------
// Hand-written (not generated) because the frontend doesn't always
// regenerate `schema.d.ts`; these mirror the utoipa-derived Rust structs
// in `backend/api/src/handlers/admin.rs`.
export interface TestLlmRequest {
  llm_id: string;
  prompt: string;
  system?: string | null;
  temperature?: number | null;
  max_tokens?: number | null;
}
export interface TestLlmResponse {
  content: string;
  prompt_tokens: number;
  completion_tokens: number;
  mocked: boolean;
}
export interface TestVoiceRequest {
  voice_id: string;
  text: string;
}
export interface TestVoiceResponse {
  audio_wav_base64: string;
  sample_rate_hz: number;
  duration_ms: number;
  mocked: boolean;
}

/** Mirrors the backend `VoicePreviewResponse` returned by
 * `GET /voices/{id}/preview`. Hand-written until `npm run gen:api`
 * picks up the new endpoint. */
export interface VoicePreviewResponse {
  audio_wav_base64: string;
  sample_rate_hz: number;
  duration_ms: number;
  mocked: boolean;
}

// --- podcasts ------------------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/podcasts.rs`.

export interface PodcastRow {
  id: string;
  title: string;
  description: string;
  has_image: boolean;
  audiobook_count: number;
  /** YouTube playlist id mirrored from this podcast — `null` until the
   *  user has connected YouTube + the playlist has been synced. */
  youtube_playlist_id: string | null;
  /** Convenience link, derived server-side from `youtube_playlist_id`. */
  youtube_playlist_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface SyncPodcastResponse {
  /** `"created"`, `"updated"`, or `"unchanged"`. */
  action: string;
  youtube_playlist_id: string | null;
  youtube_playlist_url: string | null;
}

export interface PodcastList {
  items: PodcastRow[];
}

export interface CreatePodcastRequest {
  title: string;
  description?: string | null;
  /** Optional pre-generated cover, raw base64 (no `data:` prefix). */
  image_base64?: string | null;
}

export interface UpdatePodcastRequest {
  title?: string | null;
  description?: string | null;
  /** New cover bytes, raw base64. Empty / null leaves the existing image. */
  image_base64?: string | null;
}

export interface PreviewPodcastImageRequest {
  title: string;
  description?: string | null;
  llm_id?: string | null;
}

export interface PreviewPodcastImageResponse {
  image_base64: string;
  mime_type: string;
}

/** Theme presets the animation renderer accepts. Mirror of
 * `backend/render/src/themes/index.ts::PRESETS`. */
export type AnimationTheme = "library" | "parchment" | "minimal";

// --- ideas ---------------------------------------------------------------
// Hand-written; mirrors `backend/api/src/handlers/ideas.rs`.

export type IdeaStatus = "pending" | "in_progress" | "completed";

export interface IdeaRow {
  id: string;
  title: string;
  audiobook_prompt: string;
  status: IdeaStatus;
  /** `"manual"` for user-typed entries, `"trend"` for kept LLM
   * suggestions. Free-form on the wire — treat unknown values as
   * `"manual"`. */
  source: string;
  created_at: string;
  completed_at: string | null;
  updated_at: string;
}

export interface IdeaList {
  items: IdeaRow[];
}

export interface CreateIdeaRequest {
  title: string;
  audiobook_prompt?: string | null;
  source?: string | null;
}

export interface UpdateIdeaRequest {
  title?: string | null;
  audiobook_prompt?: string | null;
  status?: IdeaStatus | null;
}

export interface SuggestIdeasRequest {
  seed?: string | null;
  language?: string | null;
  /** Clamped server-side to 1..=12. */
  count?: number | null;
}

export interface SuggestedIdea {
  title: string;
  audiobook_prompt: string;
}

export interface SuggestIdeasResponse {
  items: SuggestedIdea[];
}
